version: '3.8'

services:
  mysqldb:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: sql@1234
      MYSQL_DATABASE: klustudentdbp
    ports:
      - "3307:3306"

  backend:
    image: nikhilsivakoti/k8-backend:latest
    ports:
      - "30025:30020"
    depends_on:
      - mysqldb

  frontend:
    image: nikhilsivakoti/k8-frontend:latest
    ports:
      - "30001:80"
    depends_on:
      - backend
